/**
 * Create by sufo
 * @Email ouamour@gmail.com
 *
 * @Desc
 */

package main

import (
	"bailu/cmd"
	_ "bailu/docs" // docs is generated by Swag CLI, you have to import it.
	"bailu/global"
)

// 版本信息
//
//go:generate go env -w GO111MODULE=on
//go:generate go env -w GOPROXY=https://goproxy.cn,direct
//go:generate go mod tidy
//go:generate go mod download
//go:generate wire gen ./app
//go:generate swag init --parseDependency --parseInternal

var Version string

// 添加注释以描述 server 信息
// @title           bailu通用管理台系统
// @version         1.0
// @description     一个通用基础管理台框架
// @contact.name   Sufo
// @contact.url    https://sufo.me
// @contact.email  ouamour@gmail.com
// @host      localhost:8081
// /////////////// @BasePath
// @securityDefinitions.apikey Bearer
// @description Type "Bearer" followed by a space and JWT token.
// @in header
// @name Authorization
func main() {
	global.Version = Version
	cmd.Run()
}

//func VersionInfo() {
//	//构建信息
//	var version bool
//	versionFlag := flag.Bool("version", false, "print version information and exit")
//	flag.BoolVar(&version, "v", false, "version")
//	flag.Parse()
//	if version || *versionFlag {
//		fmt.Printf("App version: %s\ngo version:%s\nOS/Arch:%s\n", Version, runtime.Version(), runtime.GOOS)
//	}
//}
