// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/sufo/bailu-admin/app/api/admin/content"
	"github.com/sufo/bailu-admin/app/api/admin/mine"
	"github.com/sufo/bailu-admin/app/api/admin/monitor"
	"github.com/sufo/bailu-admin/app/api/admin/system"
	"github.com/sufo/bailu-admin/app/core"
	"github.com/sufo/bailu-admin/app/domain/repo"
	"github.com/sufo/bailu-admin/app/router"
	"github.com/sufo/bailu-admin/app/service/cron"
	"github.com/sufo/bailu-admin/app/service/cron/jobs"
	"github.com/sufo/bailu-admin/app/service/message"
	"github.com/sufo/bailu-admin/app/service/sys"
	"github.com/sufo/bailu-admin/pkg/casbin"
	"github.com/sufo/bailu-admin/pkg/jwt"
	"github.com/sufo/bailu-admin/pkg/log"
	"github.com/sufo/bailu-admin/pkg/sms"
	"github.com/sufo/bailu-admin/pkg/store"
	"github.com/sufo/bailu-admin/utils/captcha"
	"github.com/sufo/bailu-admin/utils/dict"
	"github.com/sufo/bailu-admin/utils/upload"
)

// Injectors from wire.go:

func BuildInjector(www string) (*Injector, func(), error) {
	iStore := store.NewStore()
	jwtProvider := &jwt.JwtProvider{
		Store: iStore,
	}
	db, cleanup, err := core.InitGorm()
	if err != nil {
		return nil, nil, err
	}
	userRepo := repo.NewUserRepo(db)
	roleRepo := repo.NewRoleRepo(db)
	casbinAdapter := &casbin.CasbinAdapter{
		UserRepo: userRepo,
		RoleRepo: roleRepo,
	}
	syncedEnforcer, cleanup2, err := InitCasbin(casbinAdapter)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dictItemRepo := repo.NewDictItemRepo(db)
	dictItemOption := sys.DictItemOption{
		DictItemRepo: dictItemRepo,
	}
	dictItemService := sys.NewDictItemService(dictItemOption)
	dictItemApi := &system.DictItemApi{
		DictItemSrv: dictItemService,
	}
	dictRepo := repo.NewDictRepo(db)
	trans := &repo.Trans{
		DB: db,
	}
	dictUtil := &dict.DictUtil{
		Store: iStore,
	}
	dictOption := sys.DictOption{
		DictRepo:     dictRepo,
		DictItemRepo: dictItemRepo,
		Trans:        trans,
		DictUtil:     dictUtil,
	}
	dictService := sys.NewDictService(dictOption)
	dictApi := &system.DictApi{
		DictSrv: dictService,
	}
	captchaStore := captcha.NewDefaultRedisStore(iStore)
	menuRepo := repo.NewMenuRepo(db)
	menuApiRepo := repo.NewMenuApiRepo(db)
	menuService := &sys.MenuService{
		MenuRepo:    menuRepo,
		MenuApiRepo: menuApiRepo,
		RoleRepo:    roleRepo,
		TranRepo:    trans,
	}
	authService := &sys.AuthService{
		UserRepo: userRepo,
		MenuSrv:  menuService,
	}
	onlineService := &sys.OnlineService{
		DB: iStore,
	}
	aliyunClient, err := sms.New()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	smsService := &sys.SMSService{
		Store: iStore,
		Sms:   aliyunClient,
	}
	loginLogRepo := repo.NewLoginLogRepo(db)
	loginLogService := sys.NewLoginLogService(loginLogRepo)
	authApi := &system.AuthApi{
		CaptchaStore: captchaStore,
		LoginSrv:     authService,
		OnlineSrv:    onlineService,
		SMSService:   smsService,
		LoginLogSrv:  loginLogService,
	}
	userOption := sys.UserOption{
		UserRepo: userRepo,
		TranRepo: trans,
		MenuRepo: menuRepo,
		Sms:      aliyunClient,
		Store:    iStore,
	}
	userService := sys.NewUserService(userOption)
	userApi := &system.UserApi{
		UserSrv: userService,
		Store:   iStore,
	}
	oss := upload.NewOSS()
	profileApi := &system.ProfileApi{
		UserSrv: userService,
		Oss:     oss,
	}
	menuApi := &system.MenuApi{
		MenuSrv: menuService,
	}
	deptRepo := repo.NewDeptRepo(db)
	deptService := sys.DeptService{
		DeptRepo:  deptRepo,
		UserRepo:  userRepo,
		TransRepo: trans,
	}
	deptApi := &system.DeptApi{
		DeptSrv: deptService,
	}
	roleOption := sys.RoleOption{
		RoleRepo:  roleRepo,
		TransRepo: trans,
	}
	roleService := sys.NewRoleService(roleOption)
	sysDeptService := &sys.DeptService{
		DeptRepo:  deptRepo,
		UserRepo:  userRepo,
		TransRepo: trans,
	}
	roleApi := &system.RoleApi{
		RoleSrv:   roleService,
		DeptSrv:   sysDeptService,
		UserSrv:   userService,
		OnlineSrv: onlineService,
	}
	postRepo := repo.NewPostRepo(db)
	postOption := sys.PostOption{
		PostRepo:  postRepo,
		UserRepo:  userRepo,
		TransRepo: trans,
	}
	postService := sys.NewPostService(postOption)
	postApi := &system.PostApi{
		PostSrv: postService,
	}
	operationRecoderRepo := repo.NewOperationRecoderRepo(db)
	operationService := &sys.OperationService{
		OperRepo: operationRecoderRepo,
	}
	operationApi := monitor.NewOperApi(operationService)
	serverInfo := monitor.NewServerInfo()
	onlineUserApi := monitor.NewOnlineUserApi(onlineService)
	taskRepo := repo.NewTaskRepo(db)
	taskLogRepo := repo.NewTaskLogRepo(db)
	noticeRepo := repo.NewNoticeRepo(db)
	noticeSendRepo := repo.NewNoticeSendRepo(db)
	noticeService := &sys.NoticeService{
		NoticeRepo:     noticeRepo,
		NoticeSendRepo: noticeSendRepo,
		UserRepo:       userRepo,
		TranRepo:       trans,
		DB:             iStore,
	}
	cronTask := cron.NewCronTask(taskRepo, taskLogRepo, noticeService)
	taskOption := cron.TaskOption{
		TaskRepo:    taskRepo,
		TaskLogRepo: taskLogRepo,
		TransRepo:   trans,
		Cron:        cronTask,
	}
	taskService := cron.NewTaskService(taskOption)
	taskApi := monitor.NewTaskApi(taskService)
	loginLogApi := monitor.NewLoginLogApi(loginLogService)
	sysConfigRepo := repo.NewSysConfigRepo(db)
	sysConfigOption := sys.SysConfigOption{
		SysConfigRepo: sysConfigRepo,
	}
	sysConfigService := sys.NewSysConfigService(sysConfigOption)
	sysConfigApi := system.NewSysConfigApi(sysConfigService)
	noticeApi := &system.NoticeApi{
		NoticeSrv: noticeService,
	}
	uploadApi := system.NewUploadApi(oss)
	messageService := &message.MessageService{
		NoticeRepo:     noticeRepo,
		NoticeSendRepo: noticeSendRepo,
		Tran:           trans,
		Dict:           dictItemService,
	}
	mineMessage := &mine.Message{
		MsgSrv: messageService,
	}
	fileRepo := repo.NewFileRepo(db)
	fileCategoryRepo := repo.NewCategoryRepo(db)
	fileOption := sys.FileOption{
		FileRepo:     fileRepo,
		CategoryRepo: fileCategoryRepo,
		Oss:          oss,
	}
	fileService := sys.NewFileService(fileOption)
	fileApi := content.NewFileApi(fileService)
	routerRouter := &router.Router{
		TokenProvider: jwtProvider,
		Enforcer:      syncedEnforcer,
		DictItemApi:   dictItemApi,
		DictApi:       dictApi,
		AuthAPI:       authApi,
		UserApI:       userApi,
		ProfileApi:    profileApi,
		MenuApi:       menuApi,
		DeptApi:       deptApi,
		RoleApi:       roleApi,
		PostApi:       postApi,
		OperApi:       operationApi,
		ServInfo:      serverInfo,
		OnlineApi:     onlineUserApi,
		TaskApi:       taskApi,
		LoginLogApi:   loginLogApi,
		ConfigApi:     sysConfigApi,
		NoticeApi:     noticeApi,
		UploadApi:     uploadApi,
		Message:       mineMessage,
		FileApi:       fileApi,
	}
	sugaredLogger, cleanup3, err := log.InitLogger()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	engine := core.InitRouter(routerRouter, sugaredLogger, www)
	scheduleNotice := jobs.NewScheduleNotice(noticeService)
	inject2Jobs := &cron.Inject2Jobs{
		Notice: scheduleNotice,
	}
	injector := &Injector{
		Engine:         engine,
		Logger:         sugaredLogger,
		Router:         routerRouter,
		MenuSrv:        menuService,
		Job:            cronTask,
		Injector2Job:   inject2Jobs,
		CasbinEnforcer: syncedEnforcer,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
